name: 打包Mac PDF拆分工具

on:
  push:
    branches: [ "main" ]  # 主分支推送时触发打包

jobs:
  build-mac-app:
    runs-on: macos-latest  # 使用GitHub提供的macOS环境
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4  # 下载你的仓库代码到Runner
        with:
          repository: ztbarefeet/pdf-splitter  # 你的远程仓库地址
          ref: main  # 检出主分支

      - name: 安装Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 选择与你本地兼容的Python版本

      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyPDF2  # 安装打包工具和PDF处理库

      - name: 执行打包命令
        run: |
          pyinstaller -w -F --name "PDF拆分工具" pdf_splitter.py  # 打包为单个Mac应用

      - name: 上传打包结果
        uses: actions/upload-artifact@v4  # 升级为最新v4版本（解决弃用问题）
        with:
          name: mac-pdf-splitter  # 工件名称（下载时显示）
          path: dist/PDF拆分工具.app  # 打包输出的.app文件路径